version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: recobook-container
    environment:
      POSTGRES_DB: RecoBookDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    restart: always